# SITE CONFIGURATION
# Hugo Blox Builder Academic Theme
# Documentation: https://docs.hugoblox.com/
# Tutorial: https://docs.hugoblox.com/tutorial/

# ============================================================================
# APPEARANCE
# ============================================================================
appearance:
  mode: system  # Options: system, light, dark
  color: emerald

# ============================================================================
# SEO & MARKETING
# ============================================================================
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Personal academic website of Ria Dutta - showcasing research, publications, and professional portfolio.'
    twitter: 'GetResearchDev'
  
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  
  verification:
    google: ''
    baidu: ''

# ============================================================================
# HEADER
# ============================================================================
header:
  navbar:
    enable: true
    blox: navbar
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: ''
      image: lotus.png

# ============================================================================
# FOOTER
# ============================================================================
footer:
  copyright:
    notice: '© {year} Ria Dutta. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# ============================================================================
# LOCALIZATION
# ============================================================================
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  # Optionally add: first_day_of_week: 0

# ============================================================================
# SITE FEATURES
# ============================================================================
features:
  math:
    enable: false
  privacy_pack:
    enable: false
